import { Trip } from '@/types/trip';

export const demoTrip: Trip = {
  id: 'demo-trip-tokyo-2024',
  destination: 'Tokyo, Japan',
  startDate: '2024-12-15',
  endDate: '2024-12-22',
  tripType: 'couple',
  createdAt: new Date().toISOString(),
  days: [
    {
      id: 'day-1',
      dayNumber: 1,
      date: '2024-12-15',
      title: 'Arrival & Shibuya Exploration',
      description: 'Touch down in Tokyo and explore the vibrant Shibuya district',
      schedule: {
        morning: [
          {
            id: 'act-1-1',
            name: 'Arrive at Narita Airport',
            description: 'Clear customs and exchange currency at airport kiosks. Pick up pocket WiFi or activate eSIM.',
            time: '10:00 AM',
            duration: '2 hours',
            cost: 0,
            category: 'relaxation',
            tags: ['arrival'],
          },
          {
            id: 'act-1-2',
            name: 'Narita Express to Tokyo',
            description: 'Take the comfortable NEX train directly to Shibuya Station.',
            time: '12:00 PM',
            duration: '90 minutes',
            cost: 35,
            category: 'relaxation',
          },
        ],
        afternoon: [
          {
            id: 'act-1-3',
            name: 'Check-in at Hotel',
            description: 'Drop off luggage and freshen up at your accommodation in Shibuya.',
            time: '2:00 PM',
            duration: '1 hour',
            cost: 0,
            category: 'relaxation',
          },
          {
            id: 'act-1-4',
            name: 'Shibuya Crossing',
            description: "Experience the world's busiest pedestrian crossing. Best viewed from Starbucks 2nd floor or the Shibuya Sky observation deck.",
            time: '3:30 PM',
            duration: '1 hour',
            cost: 0,
            category: 'culture',
            tags: ['must-see', 'photo-spot'],
          },
          {
            id: 'act-1-5',
            name: 'Shibuya Shopping',
            description: 'Explore Shibuya 109, Tokyu Hands, and the surrounding shopping streets.',
            time: '4:30 PM',
            duration: '2 hours',
            cost: 50,
            category: 'shopping',
          },
        ],
        evening: [
          {
            id: 'act-1-6',
            name: 'Dinner at Ichiran Ramen',
            description: 'Try authentic tonkotsu ramen at this famous chain with individual booth seating.',
            time: '7:00 PM',
            duration: '1 hour',
            cost: 12,
            category: 'food',
            tags: ['must-try'],
          },
          {
            id: 'act-1-7',
            name: 'Evening Walk in Harajuku',
            description: 'Stroll down Takeshita Street and explore the quirky shops and cafes.',
            time: '8:30 PM',
            duration: '1.5 hours',
            cost: 20,
            category: 'culture',
          },
        ],
      },
      travelTip: 'Get a Suica or Pasmo card for convenient travel on all trains and buses. You can purchase one at any major station.',
    },
    {
      id: 'day-2',
      dayNumber: 2,
      date: '2024-12-16',
      title: 'Traditional Tokyo - Asakusa & Ueno',
      description: 'Discover historic temples and traditional neighborhoods',
      schedule: {
        morning: [
          {
            id: 'act-2-1',
            name: 'Senso-ji Temple',
            description: "Tokyo's oldest and most famous temple. Arrive early to avoid crowds and experience the peaceful morning atmosphere.",
            time: '8:00 AM',
            duration: '2 hours',
            cost: 0,
            category: 'culture',
            tags: ['must-see', 'hidden-gem'],
          },
          {
            id: 'act-2-2',
            name: 'Nakamise Shopping Street',
            description: 'Browse traditional souvenirs, snacks, and crafts along this historic shopping street.',
            time: '10:00 AM',
            duration: '1 hour',
            cost: 30,
            category: 'shopping',
          },
        ],
        afternoon: [
          {
            id: 'act-2-3',
            name: 'Lunch at Asakusa Okonomiyaki',
            description: 'Try delicious savory Japanese pancakes at a local restaurant.',
            time: '12:00 PM',
            duration: '1 hour',
            cost: 18,
            category: 'food',
          },
          {
            id: 'act-2-4',
            name: 'Ueno Park',
            description: 'Peaceful park walk with museums, zoo, and beautiful scenery.',
            time: '2:00 PM',
            duration: '1.5 hours',
            cost: 0,
            category: 'nature',
          },
          {
            id: 'act-2-5',
            name: 'Tokyo National Museum',
            description: 'Explore Japanese art and archaeological artifacts.',
            time: '3:30 PM',
            duration: '2 hours',
            cost: 10,
            category: 'culture',
          },
        ],
        evening: [
          {
            id: 'act-2-6',
            name: 'Dinner at Ameyoko Market',
            description: 'Experience the lively street food scene with fresh seafood and local delicacies.',
            time: '6:30 PM',
            duration: '1.5 hours',
            cost: 25,
            category: 'food',
            tags: ['local-favorite'],
          },
          {
            id: 'act-2-7',
            name: 'Karaoke Night',
            description: 'Sing your heart out at a private karaoke room in Shibuya.',
            time: '8:30 PM',
            duration: '2 hours',
            cost: 30,
            category: 'nightlife',
          },
        ],
      },
      travelTip: 'Many museums are closed on Mondays. The Tokyo National Museum offers free entry on the first Sunday of each month.',
    },
    {
      id: 'day-3',
      dayNumber: 3,
      date: '2024-12-17',
      title: 'Modern Tokyo - Akihabara & TeamLab',
      description: 'Experience tech culture and digital art',
      schedule: {
        morning: [
          {
            id: 'act-3-1',
            name: 'Akihabara Electric Town',
            description: 'Explore electronics shops, anime stores, and gaming centers.',
            time: '10:00 AM',
            duration: '2.5 hours',
            cost: 40,
            category: 'culture',
            tags: ['shopping'],
          },
          {
            id: 'act-3-2',
            name: 'Maid Cafe Experience',
            description: 'Try the unique maid cafe culture (optional but very Tokyo!)',
            time: '12:30 PM',
            duration: '1 hour',
            cost: 20,
            category: 'culture',
          },
        ],
        afternoon: [
          {
            id: 'act-3-3',
            name: 'Lunch at Kanda Yabu Soba',
            description: 'Historic soba noodle restaurant established in 1880.',
            time: '2:00 PM',
            duration: '1 hour',
            cost: 15,
            category: 'food',
          },
          {
            id: 'act-3-4',
            name: 'Imperial Palace East Gardens',
            description: 'Free entry to beautiful gardens with historical significance.',
            time: '3:30 PM',
            duration: '1.5 hours',
            cost: 0,
            category: 'nature',
          },
        ],
        evening: [
          {
            id: 'act-3-5',
            name: 'TeamLab Borderless',
            description: 'Mind-blowing digital art museum. Book tickets in advance!',
            time: '6:00 PM',
            duration: '2 hours',
            cost: 35,
            category: 'culture',
            tags: ['must-see'],
          },
          {
            id: 'act-3-6',
            name: 'Dinner at Odaiba',
            description: 'Waterfront dining with views of Rainbow Bridge and Tokyo skyline.',
            time: '8:30 PM',
            duration: '1.5 hours',
            cost: 35,
            category: 'food',
          },
        ],
      },
      travelTip: 'Book TeamLab Borderless tickets at least 1 week in advance as they sell out quickly. Go on weekday evenings for fewer crowds.',
    },
    {
      id: 'day-4',
      dayNumber: 4,
      date: '2024-12-18',
      title: 'Day Trip to Nikko',
      description: 'UNESCO World Heritage shrines and natural beauty',
      schedule: {
        morning: [
          {
            id: 'act-4-1',
            name: 'Train to Nikko',
            description: 'Take the Tobu Limited Express from Asakusa Station.',
            time: '8:00 AM',
            duration: '2 hours',
            cost: 28,
            category: 'relaxation',
          },
          {
            id: 'act-4-2',
            name: 'Toshogu Shrine',
            description: 'Ornate shrine dedicated to Tokugawa Ieyasu with elaborate gold decorations.',
            time: '10:30 AM',
            duration: '2 hours',
            cost: 13,
            category: 'culture',
            tags: ['must-see'],
          },
        ],
        afternoon: [
          {
            id: 'act-4-3',
            name: 'Lunch near Shinkyo Bridge',
            description: 'Try yuba (tofu skin) dishes, a Nikko specialty.',
            time: '1:00 PM',
            duration: '1 hour',
            cost: 22,
            category: 'food',
            tags: ['local-favorite'],
          },
          {
            id: 'act-4-4',
            name: 'Lake Chuzenji',
            description: 'Scenic mountain lake with beautiful views and Kegon Falls.',
            time: '2:30 PM',
            duration: '2 hours',
            cost: 5,
            category: 'nature',
          },
        ],
        evening: [
          {
            id: 'act-4-5',
            name: 'Return to Tokyo',
            description: 'Evening train back to Tokyo.',
            time: '5:00 PM',
            duration: '2 hours',
            cost: 28,
            category: 'relaxation',
          },
          {
            id: 'act-4-6',
            name: 'Light Dinner in Shibuya',
            description: 'Grab casual food at one of the many izakayas or convenience stores.',
            time: '7:30 PM',
            duration: '1 hour',
            cost: 15,
            category: 'food',
          },
        ],
      },
      travelTip: 'Consider getting the Nikko Pass for unlimited train and bus travel. Dress warmly as Nikko is at higher elevation and cooler than Tokyo.',
    },
    {
      id: 'day-5',
      dayNumber: 5,
      date: '2024-12-19',
      title: 'Tsukiji Market & Ginza',
      description: 'Fresh seafood and luxury shopping',
      schedule: {
        morning: [
          {
            id: 'act-5-1',
            name: 'Tsukiji Outer Market',
            description: 'Explore the vibrant market with fresh seafood and street food.',
            time: '7:00 AM',
            duration: '2 hours',
            cost: 25,
            category: 'food',
            tags: ['must-try'],
          },
          {
            id: 'act-5-2',
            name: 'Sushi Breakfast',
            description: 'Enjoy incredibly fresh sushi at one of the market restaurants.',
            time: '9:00 AM',
            duration: '1 hour',
            cost: 40,
            category: 'food',
            tags: ['must-try'],
          },
        ],
        afternoon: [
          {
            id: 'act-5-3',
            name: 'Hamarikyu Gardens',
            description: 'Traditional Japanese garden with a tea house on a pond.',
            time: '11:00 AM',
            duration: '1.5 hours',
            cost: 3,
            category: 'nature',
          },
          {
            id: 'act-5-4',
            name: 'Ginza Shopping',
            description: 'Window shop at luxury boutiques and department stores.',
            time: '1:00 PM',
            duration: '3 hours',
            cost: 50,
            category: 'shopping',
          },
        ],
        evening: [
          {
            id: 'act-5-5',
            name: 'Dinner at Yakitori Alley',
            description: 'Experience authentic grilled chicken skewers under the train tracks.',
            time: '6:00 PM',
            duration: '1.5 hours',
            cost: 30,
            category: 'food',
          },
          {
            id: 'act-5-6',
            name: 'Tokyo Tower Night View',
            description: 'Iconic tower with spectacular night views of the city.',
            time: '8:00 PM',
            duration: '1.5 hours',
            cost: 20,
            category: 'culture',
          },
        ],
      },
      travelTip: 'The famous tuna auction has moved to Toyosu Market and requires advance lottery registration. Tsukiji Outer Market is still excellent for food!',
    },
    {
      id: 'day-6',
      dayNumber: 6,
      date: '2024-12-20',
      title: 'Shinjuku & Mt. Takao',
      description: 'Urban exploration and mountain hiking',
      schedule: {
        morning: [
          {
            id: 'act-6-1',
            name: 'Train to Mt. Takao',
            description: 'Easy 50-minute train ride from Shinjuku.',
            time: '8:00 AM',
            duration: '1 hour',
            cost: 5,
            category: 'relaxation',
          },
          {
            id: 'act-6-2',
            name: 'Mt. Takao Hike',
            description: 'Scenic hiking trails with great views. Can take cable car halfway if tired.',
            time: '9:30 AM',
            duration: '3 hours',
            cost: 10,
            category: 'nature',
            tags: ['adventure'],
          },
        ],
        afternoon: [
          {
            id: 'act-6-3',
            name: 'Mountain Top Lunch',
            description: 'Try tororo soba (buckwheat noodles with grated yam) at the summit.',
            time: '1:00 PM',
            duration: '1 hour',
            cost: 12,
            category: 'food',
          },
          {
            id: 'act-6-4',
            name: 'Return to Shinjuku',
            description: 'Head back to explore Shinjuku in the evening.',
            time: '3:00 PM',
            duration: '1 hour',
            cost: 5,
            category: 'relaxation',
          },
        ],
        evening: [
          {
            id: 'act-6-5',
            name: 'Omoide Yokocho',
            description: 'Atmospheric alley of tiny restaurants and yakitori stalls.',
            time: '6:00 PM',
            duration: '1.5 hours',
            cost: 25,
            category: 'food',
            tags: ['local-favorite'],
          },
          {
            id: 'act-6-6',
            name: 'Kabukicho & Golden Gai',
            description: 'Explore the entertainment district and tiny themed bars of Golden Gai.',
            time: '8:00 PM',
            duration: '2 hours',
            cost: 35,
            category: 'nightlife',
          },
        ],
      },
      travelTip: 'Mt. Takao is less crowded on weekdays. Wear comfortable hiking shoes even if taking the cable car. Some bars in Golden Gai charge cover fees.',
    },
    {
      id: 'day-7',
      dayNumber: 7,
      date: '2024-12-21',
      title: 'Relaxation & Last Minute Shopping',
      description: 'Leisurely day before departure',
      schedule: {
        morning: [
          {
            id: 'act-7-1',
            name: 'Meiji Shrine',
            description: 'Peaceful Shinto shrine surrounded by forest in the heart of Tokyo.',
            time: '9:00 AM',
            duration: '1.5 hours',
            cost: 0,
            category: 'culture',
            tags: ['must-see'],
          },
          {
            id: 'act-7-2',
            name: 'Yoyogi Park',
            description: 'Relax in the park, people-watch, and enjoy street performers.',
            time: '10:30 AM',
            duration: '1 hour',
            cost: 0,
            category: 'relaxation',
          },
        ],
        afternoon: [
          {
            id: 'act-7-3',
            name: 'Lunch at Omotesando',
            description: 'Trendy cafes and restaurants along the tree-lined avenue.',
            time: '12:00 PM',
            duration: '1.5 hours',
            cost: 28,
            category: 'food',
          },
          {
            id: 'act-7-4',
            name: 'Last-Minute Shopping',
            description: 'Pick up souvenirs at Don Quijote or local shops.',
            time: '2:00 PM',
            duration: '2 hours',
            cost: 60,
            category: 'shopping',
          },
        ],
        evening: [
          {
            id: 'act-7-5',
            name: 'Farewell Dinner',
            description: 'Splurge on a nice meal - try wagyu beef or kaiseki.',
            time: '6:00 PM',
            duration: '2 hours',
            cost: 80,
            category: 'food',
          },
          {
            id: 'act-7-6',
            name: 'Pack & Prepare',
            description: 'Organize luggage and souvenirs for departure.',
            time: '8:30 PM',
            duration: '1.5 hours',
            cost: 0,
            category: 'relaxation',
          },
        ],
      },
      travelTip: 'Check airline baggage limits before shopping. Many stores offer tax-free shopping for tourists - bring your passport!',
    },
    {
      id: 'day-8',
      dayNumber: 8,
      date: '2024-12-22',
      title: 'Departure Day',
      description: 'Safe travels home!',
      schedule: {
        morning: [
          {
            id: 'act-8-1',
            name: 'Hotel Check-out',
            description: 'Check out and head to airport.',
            time: '9:00 AM',
            duration: '1 hour',
            cost: 0,
            category: 'relaxation',
          },
          {
            id: 'act-8-2',
            name: 'Airport Transfer',
            description: 'Narita Express or airport limousine bus.',
            time: '10:00 AM',
            duration: '2 hours',
            cost: 35,
            category: 'relaxation',
          },
        ],
        afternoon: [],
        evening: [],
      },
      travelTip: 'Arrive at Narita Airport 3 hours before international flights. There are good duty-free shopping options if you have extra time!',
    },
  ],
  budget: {
    totalBudget: 3000,
    estimatedSpend: 2847,
    currency: 'USD',
    dailyAverage: 356,
    categories: [
      {
        category: 'accommodation',
        estimated: 800,
        breakdown: [
          { item: 'Hotel (7 nights)', cost: 800 },
        ],
      },
      {
        category: 'food',
        estimated: 630,
        breakdown: [
          { item: 'Meals & snacks', cost: 450 },
          { item: 'Restaurants & cafes', cost: 180 },
        ],
      },
      {
        category: 'transport',
        estimated: 280,
        breakdown: [
          { item: 'Airport transfers', cost: 70 },
          { item: 'Train passes & tickets', cost: 150 },
          { item: 'Local transport', cost: 60 },
        ],
      },
      {
        category: 'activities',
        estimated: 337,
        breakdown: [
          { item: 'Museum entries', cost: 58 },
          { item: 'TeamLab Borderless', cost: 35 },
          { item: 'Day trips', cost: 46 },
          { item: 'Entertainment', cost: 198 },
        ],
      },
      {
        category: 'miscellaneous',
        estimated: 800,
        breakdown: [
          { item: 'Shopping & souvenirs', cost: 600 },
          { item: 'Emergency fund', cost: 200 },
        ],
      },
    ],
  },
  essentials: {
    keyPhrases: [
      {
        phrase: 'Hello',
        translation: 'Konnichiwa',
        pronunciation: 'kon-nee-chee-wah',
      },
      {
        phrase: 'Thank you',
        translation: 'Arigatou gozaimasu',
        pronunciation: 'ah-ree-gah-toh go-zai-mas',
      },
      {
        phrase: 'Excuse me',
        translation: 'Sumimasen',
        pronunciation: 'soo-mee-mah-sen',
      },
      {
        phrase: 'How much?',
        translation: 'Ikura desu ka?',
        pronunciation: 'ee-koo-rah des kah',
      },
      {
        phrase: 'Where is...?',
        translation: '...wa doko desu ka?',
        pronunciation: 'wah doh-koh des kah',
      },
      {
        phrase: 'I don\'t understand',
        translation: 'Wakarimasen',
        pronunciation: 'wah-kah-ree-mah-sen',
      },
      {
        phrase: 'Delicious!',
        translation: 'Oishii!',
        pronunciation: 'oy-shee',
      },
      {
        phrase: 'Check please',
        translation: 'Okaikei onegaishimasu',
        pronunciation: 'oh-kai-keh oh-neh-gai-shee-mas',
      },
    ],
    etiquetteTips: [
      'Remove shoes when entering homes, traditional restaurants, and some temples',
      'Bow slightly when greeting people or saying thank you',
      'Don\'t tip - it\'s not customary and can be considered rude',
      'Be quiet on trains and public transport - phone calls are frowned upon',
      'Walk on the left side of escalators, stand on right',
      'Don\'t eat or drink while walking (except at festivals)',
      'Use both hands when receiving business cards or gifts',
      'Slurp your noodles - it\'s a compliment to the chef!',
      'Wait to be seated at restaurants - don\'t seat yourself',
      'Don\'t stick chopsticks upright in rice (funeral ritual)',
    ],
    generalAdvice: [
      'Japan is very cash-based - carry yen, especially for smaller shops',
      'Pocket WiFi or eSIM is essential - many places don\'t have free WiFi',
      'Convenience stores (7-Eleven, Lawson) are lifesavers for snacks and ATMs',
      'Public restrooms are extremely clean and often have high-tech toilets',
      'Most shops and restaurants don\'t speak much English - have Google Translate ready',
      'Vending machines are everywhere and offer hot and cold drinks',
      'Trains stop running around midnight - plan your evening accordingly',
      'Many museums and temples close early (around 5 PM)',
      'Queue culture is strong - always form orderly lines',
      'Trash cans are rare - carry a small bag for your trash',
    ],
    visaRequirements: 'US citizens can visit visa-free for up to 90 days for tourism',
    healthRecommendations: [
      'No vaccinations required for Japan',
      'Tap water is safe to drink throughout Japan',
      'Pharmacies (kusuriya) are common but pharmacists may not speak English',
      'International health insurance recommended',
      'Air quality is generally excellent',
    ],
    packingList: [
      'Comfortable walking shoes',
      'Light layers (buildings are heated/cooled)',
      'Small day backpack',
      'Portable charger',
      'Universal adapter (Type A/B plugs)',
      'Reusable water bottle',
      'Small towel or handkerchief',
      'Medications in original packaging',
      'Cash wallet and card holder',
      'Sunscreen and hat',
      'Umbrella (can also buy there)',
      'Zip-lock bags for wet items',
    ],
  },
  logistics: {
    neighborhoods: [
      {
        name: 'Shibuya',
        description: 'Vibrant area with shopping, nightlife, and the famous crossing. Central location.',
        why: 'Best for first-timers who want to be in the heart of the action with easy access to most attractions',
      },
      {
        name: 'Shinjuku',
        description: 'Major transport hub with endless entertainment, restaurants, and shopping options.',
        why: 'Perfect if you want nightlife and plan to take day trips (all major train lines connect here)',
      },
      {
        name: 'Asakusa',
        description: 'Traditional neighborhood near Senso-ji Temple with old Tokyo atmosphere.',
        why: 'Great for cultural experience and more affordable accommodation. Quieter at night.',
      },
      {
        name: 'Ginza',
        description: 'Upscale area with luxury shopping and fine dining.',
        why: 'Choose if you prefer a quieter, more refined experience with higher-end options',
      },
    ],
    transportation: {
      airport: 'Narita International Airport (NRT) is the main gateway. Narita Express (NEX) train takes 60-90 minutes to central Tokyo. Haneda Airport (HND) is closer but typically more expensive.',
      publicTransport: [
        'JR Yamanote Line - circular line connecting major stations',
        'Tokyo Metro & Toei Subway - extensive underground network',
        'Get a rechargeable Suica or Pasmo card for all transport',
        'Google Maps works excellently for train navigation',
        'Trains run 5 AM to midnight approximately',
      ],
      tips: [
        'Rush hour (7:30-9:30 AM, 5:30-7:30 PM) can be extremely crowded',
        'Consider a 72-hour Tokyo Metro pass if doing lots of sightseeing',
        'Train station exits can be confusing - look for numbered exits',
        'JR Pass not recommended for Tokyo-only trips',
        'Taxis are expensive but clean and safe',
        'Last trains leave around midnight - plan accordingly',
      ],
    },
    keyStations: [
      'Shibuya - Shopping, nightlife, Shibuya Crossing',
      'Shinjuku - Major hub, government building observation deck',
      'Tokyo Station - Central station, Imperial Palace nearby',
      'Asakusa - Senso-ji Temple area',
      'Ueno - Park, museums, Ameyoko market',
      'Harajuku - Youth fashion, Meiji Shrine',
    ],
  },
};
